name: DrifterLens
favicon: null
layout_spectrum: 0.4928315
typography_spectrum: 0.4408602
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: DrifterLens – Also on Flipboard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20150D'
    - '#FFFFFF'
    - '#887876'
    - '#CFBDBD'
    - '#030190'
  brandStrength: 0.6451613
  lightness: 0.7473118
  saturation: 0.6344086
  rhythmicContrast: 0.4014337
purpose: []
